using Microsoft.CodeAnalysis;
using System.Text;
using EzMap.Converters;
using EzMap.Generators.Pipelines.Mappers.Models.MappingInfos;
using EzMap.Generators.Pipelines.Mappers.Models.Mappings;

namespace EzMap.Generators.Pipelines.Mappers
{
    internal static class MappingClassCreator
    {
        internal static string CreateMappingClass(
            MapperInfo mapperInfo,
            List<PropertyMapping> mappings,
            Dictionary<string, INamedTypeSymbol> converterInstances,
            ITypeSymbol globalSettings
        )
        {
            StringBuilder sb = new();

            string domainTypeName = mapperInfo.DomainTypeSymbol.ToDisplayString();
            string dtoTypeName = mapperInfo.DtoTypeSymbol.ToDisplayString();
            string className = mapperInfo.ClassSymbol.Name;
            string namespaceName = mapperInfo.ClassSymbol.ContainingNamespace.ToDisplayString();
            bool isGlobalNameSpace = mapperInfo.ClassSymbol.ContainingNamespace.IsGlobalNamespace;
            string generatorStubName = isGlobalNameSpace
                ? className
                : $"{namespaceName}.{className}";

            ITypeSymbol converterSettings = mapperInfo.ConverterSettings ?? globalSettings;

            sb.GenerateClassHeader(className, namespaceName, isGlobalNameSpace, converterInstances, converterSettings);

            // Generate ToDomain method
            sb.GenerateMappingMethod(
                isToDomain: true,
                toTypeName: domainTypeName,
                fromTypeName: dtoTypeName,
                propertyMappings: mappings,
                generatorStubName: generatorStubName,
                customName: mapperInfo.CustomToDomainName
            );

            // Generate ToDto method
            sb.GenerateMappingMethod(
                isToDomain: false,
                toTypeName: dtoTypeName,
                fromTypeName: domainTypeName,
                propertyMappings: mappings,
                generatorStubName: generatorStubName,
                customName: mapperInfo.CustomToDtoName
            );

            sb.GenerateClassFooter(isGlobalNameSpace);

            return sb.ToString();
        }

        private static void GenerateClassHeader(
            this StringBuilder sb,
            string className,
            string namespaceName,
            bool isGlobalNamespace,
            Dictionary<string, INamedTypeSymbol> converterInstances,
            ITypeSymbol converterSettings
        )
        {
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine($"// Generated by EzMap for {className}");
            sb.AppendLine();
            if (!isGlobalNamespace)
            {
                sb.AppendLine($"namespace {namespaceName}");
                sb.AppendLine("{");
            }

            sb.AppendLine("    /// <summary>");
            sb.AppendLine($"    /// This class contains mapping methods for <see cref=\"{className}\"/>.");
            sb.AppendLine("    /// It is auto-generated by EzMap and should not be modified manually.");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine($"    public static partial class {className}");
            sb.AppendLine("    {");
            sb.AppendLine();
            sb.AppendLine($"        private static readonly {converterSettings.ToDisplayString()} _settings = new();");

            foreach (var (instanceName, converterSymbol) in converterInstances.Select(kvp => (kvp.Key, kvp.Value)))
            {
                var typeConverterInterface = converterSymbol
                    .AllInterfaces
                    .FirstOrDefault(i =>
                        i.ToDisplayString()
                            .StartsWith(
                                $"{nameof(EzMap)}.{nameof(EzMap.Converters)}.{nameof(ITypeConverter)}")
                        && i.TypeParameters.Length == 2);


                if (typeConverterInterface != null)
                {
                    sb.AppendLine(
                        $"        private static readonly {converterSymbol.ToDisplayString()} {instanceName} = new {converterSymbol.ToDisplayString()}{{ Settings = _settings }};");
                }
            }
        }

        private static void GenerateMappingMethod(
            this StringBuilder sb,
            bool isToDomain,
            string toTypeName,
            string fromTypeName,
            List<PropertyMapping> propertyMappings,
            string generatorStubName,
            string? customName = null
        )
        {
            string methodName = customName ?? (isToDomain ? "ToEntity" : "ToDto");
            string paramName = "source";

            sb.AppendLine("        /// <summary>");
            sb.AppendLine(
                $"        /// Maps an instance of <see cref=\"{fromTypeName}\"/> to <see cref=\"{toTypeName}\"/>.");
            sb.AppendLine("        /// </summary>");
            sb.AppendLine($"        /// <param name=\"{paramName}\">The source object to map from.</param>");
            sb.AppendLine($"        /// <returns>A mapped instance of <see cref=\"{toTypeName}\"/>.</returns>");
            sb.AppendLine("        /// <remarks>");
            sb.AppendLine("        /// This mapping method is auto-generated by EzMap.<br/>");
            sb.AppendLine($"        /// Generator class stub: <see cref=\"{generatorStubName}\"/>.");
            sb.AppendLine("        /// <br/><ul>");
            if (isToDomain) sb.WriteUnmappedProperties(toTypeName, propertyMappings.OfType<UnmappedDomainProperty>());
            else sb.WriteUnmappedProperties(toTypeName, propertyMappings.OfType<UnmappedDtoProperty>());
            sb.AppendLine("        /// </ul>");
            sb.AppendLine("        /// </remarks>");
            sb.AppendLine(
                $"        public static {toTypeName} {methodName}(this {fromTypeName} {paramName})");
            sb.AppendLine("        {");

            sb.AppendLine();
            sb.AppendLine($"            var dest = new {toTypeName}");
            sb.AppendLine("            {");

            // Write unmapped properties

            // Write direct mapped properties
            sb.WriteDirectMappedProperties(paramName, isToDomain, propertyMappings.OfType<DirectMappedProperty>());
            // Write converter mapped properties
            sb.WriteConverterMappedProperties(paramName, isToDomain,
                propertyMappings.OfType<ConverterMappedProperty>());
            // Write default domain mapped properties
            if (isToDomain) sb.WriteDefaultMappedProperties(propertyMappings.OfType<DefaultDomainMappedProperty>());
            else sb.WriteDefaultMappedProperties(propertyMappings.OfType<DefaultDtoMappedProperty>());

            sb.AppendLine("            };");
            sb.AppendLine("            return dest;");
            sb.AppendLine("        }");
        }

        private static void WriteDirectMappedProperties(
            this StringBuilder sb,
            string paramName,
            bool isDomain,
            IEnumerable<DirectMappedProperty> mappings
        )
        {
            foreach (var mapping in mappings)
            {
                var left = isDomain ? mapping.DomainSymbol : mapping.DtoSymbol;
                var right = isDomain ? mapping.DtoSymbol : mapping.DomainSymbol;
                sb.AppendLine($"                {left.Name} = {paramName}.{right.Name},");
            }
        }

        private static void WriteConverterMappedProperties(
            this StringBuilder sb,
            string paramName,
            bool isDomain,
            IEnumerable<ConverterMappedProperty> mappings
        )
        {
            foreach (var mapping in mappings)
            {
                var left = isDomain ? mapping.DomainSymbol : mapping.DtoSymbol;
                var right = isDomain ? mapping.DtoSymbol : mapping.DomainSymbol;
                sb.AppendLine(
                    $"                {left.Name} = {mapping.ConverterInstanceName}.Convert({paramName}.{right.Name}),");
            }
        }

        private static void WriteDefaultMappedProperties(
            this StringBuilder sb,
            IEnumerable<DefaultMappedProperty> mappings
        )
        {
            foreach (var mapping in mappings)
            {
                sb.AppendLine($"                {mapping.Symbol.Name} = {mapping.DefaultValue},");
            }
        }

        private static void WriteUnmappedProperties(
            this StringBuilder sb,
            string toTypeName,
            IEnumerable<UnmappedProperty> mappings
        )
        {
            foreach (var mapping in mappings)
            {
                sb.AppendLine(
                    $"                ///<li><see cref=\"{toTypeName}.{mapping.Symbol.Name}\"/> - Could not be auto-mapped, no matching property found.</li>");
            }
        }

        private static void GenerateClassFooter(this StringBuilder sb, bool isGlobalNamespace)
        {
            sb.AppendLine("    }");
            if (!isGlobalNamespace)
            {
                sb.AppendLine("}");
            }
        }
    }
}